* 前言
Emacs 是史上最古老的編輯器之一，然而因為許多原因，入門並不是太容易。

#+BEGIN_QUOTE
網路上雖然早就已有許許多多的 Emacs 教學，然而我當初剛開始用 Emacs 時卻依然遇到許多問題，卻無人解釋（因為熟悉的使用者都把那些視為常識就不解釋了，然而對初學者可能是難以理解的行為），想問也無從問起，也因此浪費了非常多的時間在繞遠路。這個 Emacs 101 希望可以解決這種問題，希望能讓你快速建立起清楚深刻但不多餘囉唆的基本概念，快速解決各種初學疑難雜症，該建立的概念就寫清楚避免你繞遠路浪費時間，並無痛開始使用 Emacs。

好啦這是我希望可以寫成這樣啦，歡迎大家丟 PR 一起寫。

-- kuanyui 
#+END_QUOTE

** 開始之前需要什麼預備知識嗎？
不需要很多背景知識，我想會想用 Emacs 的人應該都有點基本功夫，只要具備一點基礎的 programming 常識，例如何謂 function、variable（當然如果你已經會 Lisp 那更好）。

#+BEGIN_QUOTE
雖然我想這種人應該不多：如果你真的沒有任何程式基礎也沒關係。還是可以用 Emacs，不過當你覺得想要寫自己要的東西、需要學 Lisp 時，就多讀 ANSI Common Lisp 然後在 Emacs 裡面多玩玩 Emacs Lisp 吧。Emacs 不專屬程式設計師，只要你有興趣，一般人也是可以用的。

我當初就是完全不會寫程式時開始學 Emacs，連 function 是什麼都搞不清楚，最後也是學會了。不過當時我繞了太多遠路，學習曲線歪七扭八；希望想學的人別再繞遠路，所以我寫了這篇 Emacs 101。

-- kuanyui
#+END_QUOTE

** 可以學到什麼？
看完這一系列文章，你 *會* 知道：

  1. Emacs 適合什麼人、能拿來做什麼、優點與缺點。
  2. Emacs 的基本觀念與操作。
  3. 打造屬於自己的 Emacs。
  4. Emacs Lisp 的學習方向與開發技巧。
  5. 下一步的學習方向。

* 社群幫助

  一定要先提這個。有問題想問？遇到困難不知如何解決？Emacs 的社群相當活躍，大膽開口問吧。

** StackExchange

StackExchange 現在有 [[https://emacs.stackexchange.com/][Emacs 專版]]，相當活躍，問題很快都能找到解答。

** IRC

  這應該是目前最活躍的、也最即時的發問管道。channel 皆位於 Freenode IRC server 上：
  - 台灣（正體中文）： =#emacs.tw=
  - 國際（英文）： =#emacs=

** SNS

   也有 Google+ 與 Twitter：
  - [[https://plus.google.com/u/0/communities/115469134289640648214][Google+ 中文社群]]
  - [[https://plus.google.com/u/0/communities/114815898697665598016][Google+ 國際社群]]
  - [[https://twitter.com/EmacsTW][Emacs 台灣 (@EmacsTW) | Twitter]]
  - [[https://www.reddit.com/r/emacs/][Reddit 國際社群]]

