* 安裝 GNU Emacs

[[https://www.gnu.org/software/emacs/][GNU Emacs]] 是地球上被移植到最多平台的軟體之一，以下介紹對於在 Windows / Linux / MacOSX 下安裝與使用 Emacs 會遇到的一些問題與指引。

* Windows

** GNU Emacs

[[https://www.gnu.org/software/emacs/][在 GNU Emacs 官方首頁]] https://www.gnu.org/software/emacs/
會找到 如何下載 Emacs 的指示。

目前 GNU 已經開始提供 64 位元的 Emacs，同時這份 Emacs 25.1 也包含了對 GnuTLS 的支援，在安裝額外套件、從 Github 複製時皆能正常運作。

你只要下載最新穩定版本的壓縮檔，解壓縮後，找到 bin/runemacs，點兩下就能啟動 emacs。


** Emacs 設定檔擺放位置

對於 Linux 與 OS X，emacs 的設定檔(=.emacs.d=)是放在 =~/= (家目錄)下的，前面也有介紹過，這沒什麼問題。

在 Windows，預設的位置是 =C:\Users\<user>\AppData\Roaming= ，使用上相當不方便。請通過控制台，搜尋「環境變數」，添加變數 =HOME= 並指定到 =C:\Users\<user>= 。如此一來，就能方便的存取 =Documents= 或 =Downloads= 取得跟  Linux/macOS 一樣的使用體驗了

** 編譯工具

部分的 Emacs 套件需要使用 make、autoconf、texinfo 等工具產生文件或執行特殊編譯。另外，Windows 也沒有 Git 可用。推薦安裝 [[https://msys2.github.io][MSYS2]] https://msys2.github.io 。安裝完畢後，請把 =C:\msys2\bin= 和 =C:\msys2\user\bin= 以如同添加 =HOME= 的環境變數的步驟添加到 Windows =PATH= 列表內。

如果有缺乏的工具，可以直接 =M-x eshell= 執行 =pacman -S <package>= 安裝即可。

** 檔案編碼 換行符號

如果你同時使用 windows, Linux (or Mac)， 很可能你會發現 檔案會有換行或者是亂碼的問題。

你在 Linux (or Mac) 編輯的有中文的檔案， 在 Windows Emacs 會出現亂碼，或是你在 Windows 編輯內有中文的檔案，在 Linux (or Mac) 打開會出現亂碼。

會出現這種情況是因為 Windows 與 Linux (or Mac) 預設所使用的檔案編碼是不一樣的。

有幾種可行的處理方式
- 在檔案的開頭，指明這份檔案的編碼(以及換行符號)
- 要求 emacs 針對檔案的讀寫都使用 utf-8 的方式

*** 指定檔案使用 utf-8 編碼

在檔案的第一行或第二行加上

#+BEGIN_EXAMPLE
-*- coding: utf-8; -*-
#+END_EXAMPLE

指定 utf-8 編碼，但不指定換行符號，由所使用的作業系統決定。

#+BEGIN_EXAMPLE
-*- coding: utf-8-unix; -*-
#+END_EXAMPLE

指定 utf8 編碼，並使用 unix 換行風格。


* Mac OS X

在你的 mac 上，可能已經有比較老舊版本的 emacs 可以使用，

 雖然如此，建議你還是取得最新穩定版本的 emacs。

** Way1 - GNU Emacs For Mac OS X

[[http://emacsformacosx.com][GNU Emacs For Mac OS X]] 
這個網站已準備好最新穩定版本的 GNU Emacs 的 dmg 檔

讓我們可以下載安裝使用。

** Way2 - Homebrew

如果你想透過 homebrew 安裝 emacs 則可以這樣做

#+BEGIN_SRC sh
  brew install emacs --with-cocoa --with-rsvg  --with-gnutls --with-imagemagick
#+END_SRC

對於喜歡嚐鮮的人，我們也可以這樣去安裝最新版本的 emacs

#+BEGIN_SRC sh
  brew install emacs --HEAD --use-git-head --with-cocoa --with-gnutls --with-rsvg --with-imagemagick
#+END_SRC


* Linux

如果你使用的 Linux 發行版本有套件管理程式， 通常你都可以直接使用該套件管理程式安裝 Emacs，這邊以 Arch Linux, Debian, Ubuntu, CentOS, openSUSE 為例：

Arch Linux

#+BEGIN_SRC sh
  pacman -S emacs
#+END_SRC

Debian/Ubuntu

#+BEGIN_SRC sh
  apt-get install emacs
#+END_SRC

CentOS

#+BEGIN_SRC sh
  yum install emacs
#+END_SRC

openSUSE

#+BEGIN_SRC sh
  zypper in emacs
#+END_SRC

有時候，透過套件管理程安裝的 Emacs 不會是最新穩定的版本， 在這種情形下你可以自己下載 [[https://www.gnu.org/software/emacs/][原始碼]] 自行編譯。





